#!/usr/bin/python3
"""
a fab file to perform some configuration
"""
from fabric import Connection
from datetime import datetime

def do_pack():
    year = datetime.now().year
    month = datetime.now().month
    day = datetime.now().day
    hour = datetime.now().hour
    minutes = datetime.now().minute
    archive_name = "{}{}{}{}{}.tgz".format(year, month, day, hour, minutes)
    result = Connection.local("tar -cvzf versions/{} ./web_static".format(archive_name))
    if result.failed:
        return None
    else:
        return archine_name
